version: '3'

services:
  app:
    container_name: notifi_app
    image: fenchelfen/notifications-service:notifi_app #Specify the name of the Docker image to be built
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - project
    env_file:
      .env

  explorer:
    container_name: notifi_explorer
    image: fenchelfen/notifications-service:notifi_app
    command:
      - python3
      - app/services/explorer.py
    volumes:
      - explorer_data:/app/services/meta
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - project
    env_file:
      - .env

  postgres:
    image: postgres:12-alpine
    container_name: notifi_postgres
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notifications
    ports:
      - "5432:5432"
    networks:
      - project

volumes:
  postgres_data:
  explorer_data:

networks:
  project:
    driver: bridge