version: '3'

services:
  app:
    container_name: notifi_app
    image: fenchelfen/notifications-service:notifi_app #Specify the name of the Docker image to be built
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - nginx_network

  postgres:
    image: postgres:12-alpine
    container_name: notifi_postgres
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notifications
    ports:
      - "5432:5432"
    networks:
      - nginx_network

volumes:
  postgres_data:

networks:
  nginx_network:
    driver: bridge